version: '2'

services:
  sonarqube:
    container_name: ci-sonarqube
    image: sonarqube:6.7.1
    ports:
      - '9000:9000'
    environment:
      - SONARQUBE_JDBC_URL=jdbc:mysql://sonarqube-db:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
    depends_on:
      - sonarqube-db
    volumes:
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_extensions:/opt/sonarqube/extensions

#  sonarqube-upgrade:
#    container_name: ci-sonarqube_upgrade
#    image: sonarqube:6.7.1
#    ports:
#      - '9000:9000'
#    volumes:
#      - ./sonarqube_extensions_upgrade:/opt/sonarqube/extensions

  sonarqube-db:
    container_name: ci-sonarqube_db
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlroot
      - MYSQL_DATABASE=sonar
      - MYSQL_USER=sonar
      - MYSQL_PASSWORD=sonar
    volumes:
      - ./sonarqube_db:/var/lib/mysql

